#!/usr/bin/env python
# coding: utf-8

# Copyright 2011 Álvaro Justen
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import sys
from outputty import Table
from cStringIO import StringIO


parser = argparse.ArgumentParser(description='Show data in terminal in a '
'beautiful way, with Python')
parser.add_argument('--table', dest='table', help='Create a table',
                    action='store_true')
parser.add_argument('--to-csv', dest='to_csv', help='Export data to CSV file',
                    action='store')

args = parser.parse_args()
if not args.table:
    parser.print_help()
else:
    table = Table(from_csv=sys.stdin)
    if args.to_csv:
        table.to_csv(args.to_csv)
    else:
        print table
